{
  description = "A flake to build containers";
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs";
  };

  outputs = { self, nixpkgs }: let
    system = "x86_64-linux"; # Containers must be built for Linux
    pkgs = nixpkgs.legacyPackages.${system};
  in {
    packages.${system}.container = pkgs.dockerTools.buildImage {
      name = "my-nix-container";
      tag = "latest";
      # This (now) breaks reproducibility:
      #created = "now";
      # Contents to include in the image root
      copyToRoot = pkgs.buildEnv {
        name = "image-root";
        paths = with pkgs; [
          bashInteractive
          hello
          chrpath
          coreutils
          cpio
          diffstat
          dockerTools.binSh
          dockerTools.usrBinEnv
          dockerTools.caCertificates
          dockerTools.fakeNss
          file
          findutils
          gawk
          gcc
          git
          glibcLocalesUtf8
          gnumake
          gnused
          locale
          python3
          texinfo
          wget
          which
        ];
        pathsToLink = [ "/bin" "/etc" "/lib/locale" "/usr/bin" "/usr/share/locale" "/var" ];
      };

      config = {
        Env = [
          "LANG=en_US.UTF-8"
          "LANGUAGE=en_US:en"
          "LC_ALL=en_US.UTF-8"
          # Point to the locale archive generated by glibcLocales
          "LOCALE_ARCHIVE=/lib/locale/locale-archive"
        ];
        Cmd = [ "/bin/bash" ];
      };
    };
  };
}

