{
  description = "A flake to build containers";
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs";
  };

  outputs = { self, nixpkgs }: let
    system = "x86_64-linux"; # Containers must be built for Linux
    pkgs = nixpkgs.legacyPackages.${system};
    lib = pkgs.lib;
    ## Create a custom etc/doas.conf file for the container
    #doasConf = pkgs.writeTextDir "etc/doas.conf" ''
    #  permit nopass :wheel
    #  permit keepenv :wheel
    #'';
    fakeSudo = pkgs.writeScriptBin "sudo" ''
    #!/bin/sh
    # Just pass the command through without elevation
    exec "$@"
    '';
    lz4C = pkgs.writeScriptBin "lz4c" ''
    #!/bin/sh
    # Just pass the command through without elevation
    exec "lz4 $@"
    '';

    sharedPkgs = import ./packages.nix { inherit pkgs; } ++ [ fakeSudo lz4C ];

    # Example: Creating a basic FHS shell
    fhs = pkgs.buildFHSEnv {
      name = "my-fhs-env";
      targetPkgs = pkgs: sharedPkgs;
      runScript = "bash";
    };

  in {
    # Example: Creating a basic FHS shell
    devShells.${system}.default = fhs.env;

    packages.${system}.container = pkgs.dockerTools.buildImage {
      name = "mynix-container";
      tag = "latest";
      # This (now) breaks reproducibility:
      #created = "now";
      # Contents to include in the image root
      copyToRoot = pkgs.buildEnv {
        name = "image-root";
        paths = sharedPkgs;
        pathsToLink = [ "/bin" "/etc" "/lib/locale" "/share" "/usr/bin" "/var" ];
      };

      # This runs during the image build to create the necessary symlink
      #does not have enough perimissions: extraCommands = ''
      runAsRoot = ''
        mkdir -p share
        ln -sf ${pkgs.tzdata}/share/zoneinfo share/zoneinfo

        # Optional: Set a default local time
        mkdir -p etc
        ln -sf /share/zoneinfo/Europe/Ljubljana etc/localtime

        # Provide glibc headers:
        ln -sf ${pkgs.glibc.dev}/include /usr/include

        #rm -f /etc/group
        #rm -f /etc/passwd
      '';

      config = {
        Env = [
          "TZDIR=/share/zoneinfo"
          "LANG=en_US.UTF-8"
          "LANGUAGE=en_US:en"
          "LC_ALL=en_US.UTF-8"
          # Point to the locale archive generated by glibcLocales
          "LOCALE_ARCHIVE=/lib/locale/locale-archive"
          #"BB_ENV_PASSTHROUGH_ADDITIONS=LC_ALL LOCALE_ARCHIVE"
          "BB_ENV_PASSTHROUGH=BB_TASKHASH HOME LOGNAME PATH PWD SHELL USER LOCALE_ARCHIVE LC_ALL BBSERVER"
        ];
        Cmd = [ "/bin/bash" ];
      };
    };
  };
}

